# Generated by Django 2.2.16 on 2021-12-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211219_0329'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uniq_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('following', 'user'), name='uniq_following'),
        ),
    ]
