# Generated by Django 2.2.16 on 2021-12-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211219_0330'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uniq_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('following', 'user'), name='uniq_subscription'),
        ),
    ]
